Public Class PurchaseOrderDetail
    Public Property PurchaseOrderDetailId As Integer
    Public Property PurchaseOrderId As Integer
    Public Property LocationId As Integer
    Public Property ArticleDefId As Integer
    Public Property ArticleSize As String
    Public Property Sz1 As Double
    Public Property Sz2 As Double
    Public Property Sz3 As Double
    Public Property Sz4 As Double
    Public Property Sz5 As Double
    Public Property Sz6 As Double
    Public Property Sz7 As Double
    Public Property Qty As Double
    Public Property Price As Double
    Public Property CurrentPrice As Double
    Public Property DeliveredQty As Double
    Public Property PackPrice As Double
    Public Property Pack_Desc As String
    Public Property TaxPercent As Double
    Public Property Comments As String
    Public Property DemandID As Integer
    Public Property Item_Wise_Disc As Integer
    Public Property Pack_40Kg_Weight As Double
    Public Property AdTax_Percent As Double
    Public Property AdTax_Amount As Decimal
    Public Property PurchaseDemandDetailId As Integer
    Public Property ReceivedTotalQty As Double
    Public Property BaseCurrencyId As Integer
    Public Property BaseCurrencyRate As Double
    Public Property CurrencyId As Integer
    Public Property CurrencyRate As Double
    Public Property CurrencyAmount As Double
End Class
