Public Class SalesQuotationDetail
    Public Property QuotationDetailId As Integer
    Public Property QuotationId As Integer
    Public Property LocationId As Integer
    Public Property ArticleDefId As Integer
    Public Property ArticleSize As String
    Public Property Sz1 As Double
    Public Property Sz2 As Double
    Public Property Sz3 As Double
    Public Property Sz4 As Double
    Public Property Sz5 As Double
    Public Property Sz6 As Double
    Public Property Sz7 As Double
    Public Property Qty As Double
    Public Property Price As Double
    Public Property PostDiscountPrice As Double ''Ayesha Rehman : 28-06-2018 : OTC Bug
    Public Property CurrentPrice As Double
    Public Property DeliveredQty As Double
    Public Property SalesTax_Percentage As Double
    Public Property SchemeQty As Double
    Public Property Discount_Percentage As Double
    Public Property DeliveredSchemeQty As Double
    Public Property PurchasePrice As Double
    Public Property PackPrice As Double
    Public Property Pack_Desc As String
    Public Property Comments As String
    Public Property ItemDescription As String
    Public Property BrandName As String
    Public Property Specification As String
    Public Property RegistrationNo As String
    Public Property TradePrice As Double
    Public Property Item_Info As Boolean
    Public Property Pack_40Kg_Weight As Double
    Public Property TenderSrNo As String
    Public Property CostPrice As Double
    Public Property SED_Tax_Percent As Double
    Public Property SED_Tax_Amount As Double
    Public Property SOQuantity As Double
    Public Property DeliveredTotalQty As Double
    Public Property BaseCurrencyId As Integer
    Public Property BaseCurrencyRate As Double
    Public Property CurrencyId As Integer
    Public Property CurrencyRate As Double
    Public Property CurrencyAmount As Double
    Public Property RequirementDescription As String
    Public Property PurchaseInquiryDetailId As Integer
    Public Property VendorQuotationDetailId As Integer
    Public Property HeadArticleId As Integer
    Public Property SerialNo As String
    Public Property PurchaseInquiryId As Integer
    Public Property Alternate As Boolean
    Public Property Margin As Double
End Class
